use DB_AutoCamperRental go

EXECUTE InsertInitialCategoryEntries;

EXECUTE InsertInitialCamperEntries;

EXECUTE InsertInitialInsurancePackageEntries;

EXECUTE InsertInitialDiscountEntries;

EXECUTE InsertInitialAccountEntries;